### ISSUE TITLE
Writing tests

### ISSUE THREAD

**Issue by jskeate** [formsy/formsy-material-ui#212]
I'm using Enzyme, and trying to write some tests for a form. Is there a good way to go about this? I'm trying to use `wrapper.find(<selector>).simulate('change', <args>)`, but that doesn't seem to do anything.

**Comment by rkuykendall** [comment]
Closing as tests have been re-written to use modern enzyme and I assume @jskeate has many years ago either solved their problem or moved on :)

Sorry your issue went un-answered. If you're interested in working with Formsy and Material UI again please reach out, we are looking for contributors.
