### ISSUE TITLE
Is This Project Maintained?

### ISSUE THREAD

**Issue by robbyemmert** [formsy/formsy-material-ui#249]
The last commit was about a year ago. Is this project still being maintained, or should we look elsewhere for Material UI Formsy components?

Thanks!

**Comment by mbrookes** [comment]
Unfortunately not. (It would help if it was archived @rojobuffalo ).

Here are some alternatives:
- https://www.npmjs.com/package/react-material-ui-form-validator
- https://redux-form.com/6.6.2/examples/material-ui/
- https://github.com/foxhound87/mobx-react-form

**Comment by ea167** [comment]
For compatibility with React 16, there is a fork here:
https://www.npmjs.com/package/formsy-material-ui-react16 

Kudos to @GHermet et @martin-bb

**Comment by rkuykendall** [comment]
@rojobuffalo Would you consider transferring this project and NPM control to the Formsy organization for further development?

**Comment by mbrookes** [comment]
@rkuykendall So much has changed with both React and Material-UI since this was last updated that you're probably better off just starting from scratch (with this as reference if it's helpful).

**Comment by rojobuffalo** [comment]
@rkuykendall hi, yes I'd be happy to transfer. having said that, i'd agree with @mbrookes. these days my go-to library for dealing with forms in react is formik https://formik.org/. my apologies for leaving this unattended.

**Comment by rojobuffalo** [comment]
i could transfer or archive this repo. once it is archived we lose the ability to comment on issues like this one. still something we can do, but maybe after a ~one month delay so there's an opportunity to comment.

**Comment by mbrookes** [comment]
A transfer is nicer in a couple of ways, in that it maintains some history, even if the update is a complete rewrite. And anyone coming across a link to this repo will get redirected to its new location. (TBH I didn't know Formsy was still maintained until this popped up!)

**Comment by rkuykendall** [comment]
I think the biggest perks of a transfer-with-redirect would be getting all the users searching for "Formsy Material UI" immediately and letting them know we are working on this implementation and open to help. Based on the issues and pull requests, this was a pretty popular Formsy implementation, so I bet it's still getting traffic. We cloned instead of transferring from `christianalfoni/formsy-react` and I regret it, as the old repo was the top Google result for at least a year going forward. This repo is the #3 result for "Formsy" on Github, and it would be nice if that wasn't an abandoned project. 

It's also a nice name, `formsy-material-ui`. I suspect if we get a lot of repos under the project, we'll switch to an `@formsy/material-ui` pattern, but I'd rather just use the old names for now.

**Comment by mbrookes** [comment]
"Make it so"

**Comment by rojobuffalo** [comment]
@rkuykendall I just attempted to transfer to the formsy organization but got an error:
![image](https://user-images.githubusercontent.com/3956993/100961973-a4f88080-34e0-11eb-9539-50d5383803dc.png)

**Comment by rkuykendall** [comment]
I've invited you both to the organization. This should allow @rojobuffalo to make the transfer, and adding [rkuykendall](https://www.npmjs.com/~rkuykendall) to the npm project should allow me to publish. @mbrookes you're welcome to join or not, you'll still be credited in the readme regardless. And same to you @rojobuffalo, feel free to drop the org once the transfer is complete if you'd like.

**Comment by rojobuffalo** [comment]
@rkuykendall i just transferred the repo and added you to the npm package. thanks for taking it on. feel free to tag me on any PRs if I can help

**Comment by rkuykendall** [comment]
Hey @mbrookes! I'm ready to do the first new release of `formsy-material-ui` (just infrastructure improvements so far, but looking good) and it doesn't appear I have publish rights on [the NPM project on npmjs.com](https://www.npmjs.com/package/formsy-material-ui). As far as I can tell, I'm not on the project at all. Would you mind double checking?

**Comment by rkuykendall** [comment]
( also tagging @rojobuffalo because I you might also have the ability to add me to the npmjs.com package )

**Comment by ryanblakeley** [comment]
@rkuykendall hey i sent you an invite to publish on npm
